# Generated by Django 2.1.5 on 2019-01-26 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20190126_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user_post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
