# Generated by Django 2.1.5 on 2019-04-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_post_tagged_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tagging',
            field=models.TextField(blank=True),
        ),
    ]
