# Generated by Django 2.1.5 on 2019-04-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_post_tagging'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='want_to_tag',
            field=models.BooleanField(null=True),
        ),
    ]
